apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garudapass

resources:
  - namespace.yaml
  - postgresql.yaml
  - redis.yaml
  - keycloak.yaml
  - bff.yaml
  - services.yaml
  - monitoring.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
  - pdb.yaml
