apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garudapass-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: bff
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: development
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "250m"
  - target:
      kind: Deployment
      name: keycloak
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

namePrefix: dev-
commonLabels:
  environment: development
