FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bff .

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /bff /bff
EXPOSE 4000
CMD ["/bff"]
