// Package audithttp provides HTTP middleware that automatically emits
// audit events for API operations. Captures method, path, status,
// actor, and timing for compliance with PP 71/2019 audit requirements.
package audithttp

import (
	"net/http"
	"strings"
	"time"
)

// Event represents an audit event generated by the middleware.
type Event struct {
	Timestamp  time.Time `json:"timestamp"`
	Method     string    `json:"method"`
	Path       string    `json:"path"`
	StatusCode int       `json:"status_code"`
	UserID     string    `json:"user_id,omitempty"`
	TenantID   string    `json:"tenant_id,omitempty"`
	RemoteAddr string    `json:"remote_addr"`
	UserAgent  string    `json:"user_agent"`
	Duration   time.Duration `json:"duration"`
	Action     string    `json:"action"` // Derived from method.
	Resource   string    `json:"resource"` // Derived from path.
	RequestID  string    `json:"request_id,omitempty"`
}

// Emitter receives audit events.
type Emitter interface {
	Emit(event Event)
}

// EmitterFunc adapts a function to the Emitter interface.
type EmitterFunc func(Event)

func (f EmitterFunc) Emit(event Event) { f(event) }

// Config controls audit middleware behavior.
type Config struct {
	Emitter    Emitter
	SkipPaths  map[string]bool // Paths to skip (e.g., /healthz).
	UserHeader string          // Header containing user ID (default: X-User-ID).
	TenantHeader string        // Header containing tenant ID (default: X-Tenant-ID).
}

// Middleware returns HTTP middleware that emits audit events.
func Middleware(cfg Config) func(http.Handler) http.Handler {
	if cfg.UserHeader == "" {
		cfg.UserHeader = "X-User-ID"
	}
	if cfg.TenantHeader == "" {
		cfg.TenantHeader = "X-Tenant-ID"
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if cfg.SkipPaths != nil && cfg.SkipPaths[r.URL.Path] {
				next.ServeHTTP(w, r)
				return
			}

			start := time.Now()

			rw := &statusWriter{ResponseWriter: w, status: http.StatusOK}
			next.ServeHTTP(rw, r)

			if cfg.Emitter != nil {
				cfg.Emitter.Emit(Event{
					Timestamp:  start,
					Method:     r.Method,
					Path:       r.URL.Path,
					StatusCode: rw.status,
					UserID:     r.Header.Get(cfg.UserHeader),
					TenantID:   r.Header.Get(cfg.TenantHeader),
					RemoteAddr: r.RemoteAddr,
					UserAgent:  r.Header.Get("User-Agent"),
					Duration:   time.Since(start),
					Action:     methodToAction(r.Method),
					Resource:   extractResource(r.URL.Path),
					RequestID:  r.Header.Get("X-Request-ID"),
				})
			}
		})
	}
}

type statusWriter struct {
	http.ResponseWriter
	status      int
	wroteHeader bool
}

func (sw *statusWriter) WriteHeader(code int) {
	if !sw.wroteHeader {
		sw.status = code
		sw.wroteHeader = true
		sw.ResponseWriter.WriteHeader(code)
	}
}

func (sw *statusWriter) Write(b []byte) (int, error) {
	if !sw.wroteHeader {
		sw.WriteHeader(http.StatusOK)
	}
	return sw.ResponseWriter.Write(b)
}

func methodToAction(method string) string {
	switch method {
	case http.MethodGet, http.MethodHead:
		return "READ"
	case http.MethodPost:
		return "CREATE"
	case http.MethodPut, http.MethodPatch:
		return "UPDATE"
	case http.MethodDelete:
		return "DELETE"
	default:
		return "ACCESS"
	}
}

func extractResource(path string) string {
	// Extract the resource type from the path (e.g., /api/v1/users/123 → users).
	parts := strings.Split(strings.Trim(path, "/"), "/")
	for i := len(parts) - 1; i >= 0; i-- {
		// Skip version prefixes and IDs.
		p := parts[i]
		if p == "" || strings.HasPrefix(p, "v") || isID(p) {
			continue
		}
		return p
	}
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "unknown"
}

func isID(s string) bool {
	// Simple heuristic: UUIDs, numeric IDs.
	if len(s) == 36 && strings.Count(s, "-") == 4 {
		return true
	}
	for _, c := range s {
		if c < '0' || c > '9' {
			return false
		}
	}
	return len(s) > 0 && len(s) <= 20
}
