// Package sdkgen generates Go SDK client code from API route definitions.
package sdkgen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// Endpoint describes an API endpoint for code generation.
type Endpoint struct {
	Method       string   // GET, POST, etc.
	Path         string   // /api/v1/sign/certificates
	Description  string
	RequestType  string // Go type name for request body
	ResponseType string // Go type name for response
	AuthRequired bool
	PathParams   []string // extracted from {param} in path
}

// SDKConfig for generating SDK code.
type SDKConfig struct {
	PackageName string
	ServiceName string
	BaseURL     string
	Endpoints   []Endpoint
}

// ExtractPathParams extracts path parameters from a URL path pattern.
// E.g., "/api/v1/users/{user_id}/certs/{cert_id}" returns ["user_id", "cert_id"].
func ExtractPathParams(path string) []string {
	var params []string
	for {
		start := strings.Index(path, "{")
		if start == -1 {
			break
		}
		end := strings.Index(path[start:], "}")
		if end == -1 {
			break
		}
		params = append(params, path[start+1:start+end])
		path = path[start+end+1:]
	}
	return params
}

const sdkTemplate = `// Code generated by sdkgen. DO NOT EDIT.
package {{.PackageName}}

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// {{.ServiceName}}Client is the SDK client for the {{.ServiceName}} API.
type {{.ServiceName}}Client struct {
	baseURL    string
	httpClient *http.Client
	apiKey     string
}

// New{{.ServiceName}}Client creates a new {{.ServiceName}} API client.
func New{{.ServiceName}}Client(baseURL string, opts ...ClientOption) *{{.ServiceName}}Client {
	c := &{{.ServiceName}}Client{
		baseURL:    baseURL,
		httpClient: http.DefaultClient,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// ClientOption configures the SDK client.
type ClientOption func(*{{.ServiceName}}Client)

// WithHTTPClient sets a custom HTTP client.
func WithHTTPClient(hc *http.Client) ClientOption {
	return func(c *{{.ServiceName}}Client) {
		c.httpClient = hc
	}
}

// WithAPIKey sets the API key for authenticated requests.
func WithAPIKey(key string) ClientOption {
	return func(c *{{.ServiceName}}Client) {
		c.apiKey = key
	}
}

{{range .Endpoints}}
// {{methodName .}} {{.Description}}
func (c *{{$.ServiceName}}Client) {{methodName .}}({{methodParams .}}) {{methodReturn .}} {
	{{- if pathParamReplacements .}}
	path := fmt.Sprintf("{{pathFmt .}}", {{pathArgs .}})
	{{- else}}
	path := "{{.Path}}"
	{{- end}}

	{{- if hasBody .}}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return {{zeroReturn .}}fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequest("{{.Method}}", c.baseURL+path, bytes.NewReader(body))
	{{- else}}
	req, err := http.NewRequest("{{.Method}}", c.baseURL+path, nil)
	{{- end}}
	if err != nil {
		return {{zeroReturn .}}fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	{{- if .AuthRequired}}
	if c.apiKey != "" {
		req.Header.Set("X-API-Key", c.apiKey)
	}
	{{- end}}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return {{zeroReturn .}}fmt.Errorf("execute request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		errBody, _ := io.ReadAll(resp.Body)
		return {{zeroReturn .}}fmt.Errorf("API error %d: %s", resp.StatusCode, string(errBody))
	}

	{{- if .ResponseType}}
	var result {{.ResponseType}}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return {{zeroReturn .}}fmt.Errorf("decode response: %w", err)
	}
	return result, nil
	{{- else}}
	return nil
	{{- end}}
}
{{end}}
`

const typesTemplate = `// Code generated by sdkgen. DO NOT EDIT.
package {{.PackageName}}
{{range .Endpoints}}
{{- if .RequestType}}
// {{.RequestType}} is the request body for {{.Description}}.
type {{.RequestType}} struct {
	// TODO: define fields for {{.RequestType}}
}
{{end}}
{{- if .ResponseType}}
// {{.ResponseType}} is the response for {{.Description}}.
type {{.ResponseType}} struct {
	// TODO: define fields for {{.ResponseType}}
}
{{end}}
{{- end}}
`

// GenerateGoSDK generates a Go SDK client from endpoint definitions.
func GenerateGoSDK(cfg SDKConfig) (string, error) {
	// Ensure path params are populated.
	for i := range cfg.Endpoints {
		if len(cfg.Endpoints[i].PathParams) == 0 {
			cfg.Endpoints[i].PathParams = ExtractPathParams(cfg.Endpoints[i].Path)
		}
	}

	funcMap := template.FuncMap{
		"methodName":            methodName,
		"methodParams":          methodParams,
		"methodReturn":          methodReturn,
		"hasBody":               hasBody,
		"zeroReturn":            zeroReturn,
		"pathFmt":               pathFmt,
		"pathArgs":              pathArgs,
		"pathParamReplacements": pathParamReplacements,
	}

	tmpl, err := template.New("sdk").Funcs(funcMap).Parse(sdkTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return buf.String(), nil
}

// GenerateGoTypes generates Go type definitions from endpoint descriptions.
func GenerateGoTypes(cfg SDKConfig) (string, error) {
	tmpl, err := template.New("types").Parse(typesTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}
	return buf.String(), nil
}

func methodName(ep Endpoint) string {
	// Build a method name from the HTTP method and path.
	parts := strings.Split(strings.Trim(ep.Path, "/"), "/")
	var name string
	switch ep.Method {
	case "GET":
		name = "Get"
	case "POST":
		name = "Create"
	case "PUT":
		name = "Update"
	case "DELETE":
		name = "Delete"
	case "PATCH":
		name = "Patch"
	default:
		name = ep.Method
	}
	for _, p := range parts {
		if strings.HasPrefix(p, "{") {
			continue
		}
		// Skip common prefixes.
		if p == "api" || p == "v1" || p == "v2" {
			continue
		}
		name += capitalize(p)
	}
	return name
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func methodParams(ep Endpoint) string {
	var params []string
	for _, p := range ep.PathParams {
		params = append(params, toCamelCase(p)+" string")
	}
	if hasBody(ep) {
		params = append(params, "reqBody "+ep.RequestType)
	}
	return strings.Join(params, ", ")
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = capitalize(parts[i])
	}
	return strings.Join(parts, "")
}

func methodReturn(ep Endpoint) string {
	if ep.ResponseType != "" {
		return "(" + ep.ResponseType + ", error)"
	}
	return "error"
}

func hasBody(ep Endpoint) bool {
	return ep.RequestType != "" && (ep.Method == "POST" || ep.Method == "PUT" || ep.Method == "PATCH")
}

func zeroReturn(ep Endpoint) string {
	if ep.ResponseType != "" {
		return ep.ResponseType + "{}, "
	}
	return ""
}

func pathFmt(ep Endpoint) string {
	result := ep.Path
	for _, p := range ep.PathParams {
		result = strings.Replace(result, "{"+p+"}", "%s", 1)
	}
	return result
}

func pathArgs(ep Endpoint) string {
	var args []string
	for _, p := range ep.PathParams {
		args = append(args, toCamelCase(p))
	}
	return strings.Join(args, ", ")
}

func pathParamReplacements(ep Endpoint) bool {
	return len(ep.PathParams) > 0
}
